site_name: Portfolio
theme:
  name: material
site_name: Moje projekty
site_author: Aleksandra Binkiewicz
site_url: https://abinkiewicz.github.io/data_science_portfolio
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!
    
repo_name: abinkiewicz/ds_ai_portfolio
repo_url: https://github.com/abinkiewicz/data_science_portfolio

theme:
  name: material

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "PreorderMe": preorder_me/index.md
- Poprzednie projekty:
  - "TranscriptMe": transcript_me/index.md

