site_name: Portfolio
theme:
  name: material
site_name: Moje projekty
site_author: Aleksandra Binkiewicz
site_url: https://abinkiewicz.github.io/data_science_portfolio
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: abinkiewicz/ds_ai_portfolio
repo_url: https://github.com/abinkiewicz/data_science_portfolio

theme:
  name: material
  palette:

    # Automatyczny tryb (bazuje na ustawieniach systemu)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep-purple
      accent: deep-purple

    # Tryb jasny
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep-purple
      accent: deep-purple

    # Tryb ciemny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: deep-purple
      accent: deep-purple


nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "PreorderMe": preorder_me/index.md
- Poprzednie projekty:
  - "TranscriptMe": transcript_me/index.md