site_name: Portfolio
theme:
  name: material
site_name: Moje projekty
site_author: Aleksandra Binkiewicz
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

theme:
  name: material

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "PreorderMe": preorder_me/index.md
- Poprzednie projekty:
  - "TranscriptMe": transcript_me/index.md
